homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 5
  unit_system: metric
  time_zone: Asia/Shanghai
  customize: !include customize.yaml
  whitelist_external_dirs:
    - '/config/downloads'
    - '/tmp'
    - '/config/downloads/camera/'
  # packages: 
  #   gaodetraffic: !include packages/gaodetraffic.yaml
  #   caiyunweatherse: !include packages/caiyunweatherse.yaml
  packages: !include_dir_named packages

system_health:

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 1000
    # icon: mdi:account-multiple

device_tracker:

mqtt:
  broker: 192.168.2.173
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass
  discovery: true
  # discovery_prefix: homeassistant

xiaomi_aqara:
  gateways:
    - mac: 7C49EB84897B
      key: UFAC9RFMV24R39QF
    - mac: 7C49EB86104E
      key: NSCT47U3M3039UKS
    
ifttt:
  key: !secret ifttt_key
# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

auth_providers:
   - type: legacy_api_password
     api_password: !secret http_password

http:
  api_password: !secret http_password

updater:

discovery:

ios:

homekit:
  filter:
    include_domains:
      - alarm_control_panel
      - light
      - media_player
      - switch
    exclude_entities:
      - switch.dafang_blue_led
      - switch.dafang_ir_led
      - switch.dafang_h264_rtsp_server
      - switch.dafang_mjpeg_rtsp_server
      - switch.dafang_ir_filter
      - switch.dafang_motion_detection
      - switch.dafang_motion_send_mail
      - switch.dafang_motion_send_telegram
      - switch.dafang_motion_tracking
      - switch.dafang_night_mode
      - switch.dafang_night_mode_auto
      - switch.dafang_yellow_led
  entity_config:
    alarm_control_panel.home_alarm:
      code: 1568

downloader:
  download_dir: downloads
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - sensor
      - switch
# View all events in a logbook
logbook: !include logbook.yaml

climate:
  - platform: saswell
    username: !secret saswell_user
    password: !secret saswell_pass
    scan_interval: 300
    # devices: 7
    
influxdb:
  host: localhost
  port: 8086

camera:
  - platform: generic
    name: DaFang3
    username: !secret dafang_user
    password: !secret dafang_pass
    authentication: basic
    still_image_url: https://192.168.2.165/cgi-bin/currentpic.cgi
    verify_ssl: false
    scan_interval: 5
  - platform: generic
    name: WestWindow
    username: !secret hik_user
    password: !secret hik_pass
    authentication: digest
    verify_ssl: false
    still_image_url: http://192.168.2.2/ISAPI/Streaming/channels/101/picture
    scan_interval: 5
  - platform: generic
    name: AcLocation
    username: !secret hik_user
    password: !secret hik_pass
    authentication: digest
    verify_ssl: false
    still_image_url: http://192.168.2.3/ISAPI/Streaming/channels/101/picture
    scan_interval: 5
  - platform: generic
    name: FrontYard
    username: !secret hik_user
    password: !secret hik_pass
    authentication: digest
    verify_ssl: false
    still_image_url: http://192.168.2.4/ISAPI/Streaming/channels/101/picture
    scan_interval: 5
  - platform: generic
    name: BackDoor
    username: !secret hik_user
    password: !secret hik_pass
    authentication: digest
    verify_ssl: false
    still_image_url: http://192.168.2.5/ISAPI/Streaming/channels/101/picture
    scan_interval: 5
  - platform: generic
    name: KitchenWindow
    username: !secret hik_user
    password: !secret hik_pass
    authentication: digest
    verify_ssl: false
    still_image_url: http://192.168.2.6/ISAPI/Streaming/channels/101/picture
    scan_interval: 5
  - platform: generic
    name: EastWall
    username: !secret hik_user
    password: !secret hik_pass
    authentication: digest
    verify_ssl: false
    still_image_url: http://192.168.2.7/ISAPI/Streaming/channels/101/picture
    scan_interval: 5
  - platform: generic
    name: LivingRoom
    username: !secret hik_user
    password: !secret hik_mainpass
    authentication: digest
    verify_ssl: false
    still_image_url: http://192.168.2.186/ISAPI/Streaming/channels/701/picture
    scan_interval: 5
  - platform: generic
    name: FrontDoor
    username: !secret hik_user
    password: !secret hik_mainpass
    authentication: digest
    verify_ssl: false
    still_image_url: http://192.168.2.186/ISAPI/Streaming/channels/801/picture
    scan_interval: 10

image_processing:
  # - platform: deepstack_object
  #   ip_address: 192.168.2.21
  #   port: 8088
  #   scan_interval: 20000
  #   target: person
  #   source:
  #     - entity_id: camera.dafang3
  #       name: deepstack_dafang3
  #     - entity_id: camera.livingroom
  #       name: deepstack_livingroom
  #     - entity_id: camera.frontdoor
  #       name: deepstack_frontdoor

recorder:
  purge_interval: 2
  purge_keep_days: 2
  db_url: !secret mysql_db_url
# Enables a map showing the location of tracked devices
# map:
panel_custom:
  - name: inkwavemap
    sidebar_title: '地图'
    sidebar_icon: mdi:map
    url_path: inkwavemap

# Track the sun
sun:

notify:
  - platform: group
    name: iOS
    services:
      - service: ios_tristones_iphone6s
  - name: ph
    platform: pushover
    api_key: !secret pushover_key
    user_key: !secret pushover_token
    services:
      - service: ph

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: 1568
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
      delay_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 30
      delay_time: 20

# Weather prediction
sensor:
  # - platform: yr
  - platform: mqtt
    state_topic: 'stat/kqzl'
    name: 'Jia Quan'
    unit_of_measurement: 'μg/m3'
    value_template: '{{ value_json.jiaquan }}'
  - platform: mqtt
    state_topic: 'stat/kqzl'
    name: 'PM2.5'
    unit_of_measurement: 'μg/m3'
    value_template: '{{ value_json.pm2p5 }}'

binary_sensor: !include binary_sensor.yaml

switch: !include switch.yaml

# switch:
#   - platform: broadlink
#     name: "broadlink1"
#     host: '192.168.2.152'    
#     mac: '78:0F:77:00:8E:8B'
#     friendly_name: '空气净化器'
#     switches:
#       air_living_on:
#         friendly_name: '空净开关'
#         command_on: 'JgAMAXQ3ESgRDBANEA0OKxANDw4PDRANDyoQDRApECkQDQ8qECkRKBEoESkQDBEoEQwRDBApEQwQDRANEAwRKBEpECkQKRANEAwRDBEMEA0QDRAMEQwQDRANEA0QDBEMDw4QDRANEAwRDBEMEA0QDRAMEQwRDBANECkQDRAMESkQKRApEA0QAAPWdDcRKBEMEQwQDRApEA0QDRAMEQwRKBEMESgRKBEMECkRKBEoESgRKBEMESgRDBEMECkRDBANEA0QDBEMEQwQDRANECkQKRApECkQDRAMEQwRKBEoEQwRDBEMEA0QDRAMEQwRDBANEA0QDBEMEQwQDRANEAwRKBENEAwQKREMEA0QDRAADQUAAAAAAAAAAAAAAAA=' 
#         command_off: 'JgAMAXQ3ESgRDBANEA0OKxANDw4PDRANDyoQDRApECkQDQ8qECkRKBEoESkQDBEoEQwRDBApEQwQDRANEAwRKBEpECkQKRANEAwRDBEMEA0QDRAMEQwQDRANEA0QDBEMDw4QDRANEAwRDBEMEA0QDRAMEQwRDBANECkQDRAMESkQKRApEA0QAAPWdDcRKBEMEQwQDRApEA0QDRAMEQwRKBEMESgRKBEMECkRKBEoESgRKBEMESgRDBEMECkRDBANEA0QDBEMEQwQDRANECkQKRApECkQDRAMEQwRKBEoEQwRDBEMEA0QDRAMEQwRDBANEA0QDBEMEQwQDRANEAwRKBENEAwQKREMEA0QDRAADQUAAAAAAAAAAAAAAAA='
#       air_living_auto:
#         friendly_name: '空净自动'
#         command_on: 'JgAMAXQ3ECkQDQ4PEA0QKRANEQsQDREMECkQDRApDisQDRApECkOKw4rDisQDQ4rDg8ODw4rDg8ODg8ODg8OKw4rDisOKw8ODg8ODw4PDg4PDg4PDg8ODw4PDg4ODw4PDg8ODw4ODg8ODw4PDg8PDRANEA0ODw4PDisODg8ODisOKw4rDw4OAAPZdDcQKRANEA0ODw8qEA0PDRANEA0QKRANECkQKRANDisQKRApDisQKQ4PDisODxANECkQDQ4ODw4ODw4PDg8PDRANECkOKxApECoODg8ODg8OKw4PDisODw4PDg4ODw4PDg8ODw4ODg8ODw4PDg8ODhANDisOKw4PDg8OKw4PDg8ODg8ADQUAAAAAAAAAAAAAAAA='
#         command_off: 'JgAMAXQ3ECkQDQ4PEA0QKRANEQsQDREMECkQDRApDisQDRApECkOKw4rDisQDQ4rDg8ODw4rDg8ODg8ODg8OKw4rDisOKw8ODg8ODw4PDg4PDg4PDg8ODw4PDg4ODw4PDg8ODw4ODg8ODw4PDg8PDRANEA0ODw4PDisODg8ODisOKw4rDw4OAAPZdDcQKRANEA0ODw8qEA0PDRANEA0QKRANECkQKRANDisQKRApDisQKQ4PDisODxANECkQDQ4ODw4ODw4PDg8PDRANECkOKxApECoODg8ODg8OKw4PDisODw4PDg4ODw4PDg8ODw4ODg8ODw4PDg8ODhANDisOKw4PDg8OKw4PDg8ODg8ADQUAAAAAAAAAAAAAAAA='
#       air_living_power:
#         friendly_name: '空净强力'
#         command_on: 'JgAMAXM4ECoPDRANDw4OKw4PDg8ODw4ODisPDg4rDisPDg4rDisPKw4rDisODw4rDg4ODw4rDg8ODw4PDg8OKw4rDyoPKg8ODw4ODg4PDg8ODw4PDg4ODw4PDg8ODw4ODg8ODw4PDg8ODg4PDg8ODw4PDg4ODw4PDisPDg4PDisPKg8qDw4PAAPXdDgQKQ8ODw0QDQ4rDg8QDQ4PDw0PKw8NDyoRKQ8NDyoQKREpDyoPKg8ODyoPDRANDyoQDQ8ODg8PDg8NDg8PDg4PDisOKw4rDisODw8ODg8OKw8NEA0QDQ8qEA0PDg8ODg4ODw4PDg8ODw4ODg8ODw4PDisODw4PDisOKw4PDg4ODw4ADQUAAAAAAAAAAAAAAAA='
#         command_off: 'JgAMAXM4ECoPDRANDw4OKw4PDg8ODw4ODisPDg4rDisPDg4rDisPKw4rDisODw4rDg4ODw4rDg8ODw4PDg8OKw4rDyoPKg8ODw4ODg4PDg8ODw4PDg4ODw4PDg8ODw4ODg8ODw4PDg8ODg4PDg8ODw4PDg4ODw4PDisPDg4PDisPKg8qDw4PAAPXdDgQKQ8ODw0QDQ4rDg8QDQ4PDw0PKw8NDyoRKQ8NDyoQKREpDyoPKg8ODyoPDRANDyoQDQ8ODg8PDg8NDg8PDg4PDisOKw4rDisODw8ODg8OKw8NEA0QDQ8qEA0PDg8ODg4ODw4PDg8ODw4ODg8ODw4PDisODw4PDisOKw4PDg4ODw4ADQUAAAAAAAAAAAAAAAA='
#       ac_living_power:
#         friendly_name: '客厅空调开关'
#         command_on:   'JgBoAMv2FXMWcxV0FTAVdBV0FHQVdBQxFTEWLhV1FDAVMRUxFTAWLxV0FXQWLxUwFTEVMRVzFXQVMBcuFXQVdBR0FXQVMBUwFXQVMRV0FDEVdBQxFTAXchYvFXMVMRVzFTEVcxZzF/YWAA0F'
#         command_off:  'JgBoAMv2FXMWcxV0FTAVdBV0FHQVdBQxFTEWLhV1FDAVMRUxFTAWLxV0FXQWLxUwFTEVMRVzFXQVMBcuFXQVdBR0FXQVMBUwFXQVMRV0FDEVdBQxFTAXchYvFXMVMRVzFTEVcxZzF/YWAA0F'

# Text to speech
tts:
  - platform: google
  - platform: baidu
    app_id: !secret baidu_tts_api_id
    api_key: !secret baidu_tts_api_key
    secret_key: !secret baidu_tts_secret_key

logger:
  default: critical
  logs:
    homeassistant.components.influxdb: critical
    homeassistant.components.image_processing: critical
    homeassistant.core: critical
    homeassistant.components.media_player: critical
    homeassistant.components.camera.generic: critical

# Cloud
cloud:

input_boolean:
  irrigate_switch:
    name: "草坪手动浇灌" 
    initial: off
    icon: mdi:water-pump

input_number:
  lawn_timer_minutes:
    name: "分钟"
    initial: 2
    min: 1
    max: 15
    step: 1
    icon: mdi:timer


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
