sensor:
  - platform: gaodetraffic
    scan_interval: 350
    name: nbgj_traffic
    api_key: !secret gaode_api_key
    road_name: 南北高架路
    city:  上海
  - platform: gaodetraffic
    scan_interval: 350
    name: ghxl_traffic
    api_key: !secret gaode_api_key
    road_name: 共和新路
    city:  上海
  - platform: gaodetraffic
    scan_interval: 350
    name: zhl_traffic
    api_key: !secret gaode_api_key
    road_name: 中环路
    city:  上海

group:
  gaodetraffic:
    name: 交通态势
    view: yes 
    # icon: mdi:traffic-light
    entities:
    - sensor.nbgj_traffic
    - sensor.ghxl_traffic
    - sensor.zhl_traffic

homeassistant:
  customize:
    sensor.zhl_traffic:
      friendly_name: 中环路
      # icon: mdi:traffic-light
    sensor.ghxl_traffic:
      friendly_name: 共和新路
      # icon: mdi:traffic-light
    sensor.nbgj_traffic:
      friendly_name: 南北高架路
      # icon: mdi:traffic-light
